[versions]
agp = "7.2.2"
google_services = "4.3.2"
kotlin = "1.5.30"

[libraries]

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
android_library = { id = "com.android.library", version.ref = "agp" }
google_services = { id = "com.google.gms.google-services", version.ref = "google_services" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_android_extensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "kotlin" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.44.0" }
