[versions]
agp = "7.4.2"
google_services = "4.3.2"
kotlin = "1.7.22"

[libraries]
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx_annotation = "androidx.annotation:annotation:1.1.0"
androidx_appcompant = "androidx.appcompat:appcompat:1.1.0"
androidx_constraintlayout = "androidx.constraintlayout:constraintlayout:1.1.3"
androidx_core = "androidx.core:core-ktx:1.3.0"
androidx_recyclerview = "androidx.recyclerview:recyclerview:1.1.0"
androidx_transition = "androidx.transition:transition:1.3.1"
firebase_auth = "com.google.firebase:firebase-auth:19.3.2"
firebase_authui = "com.firebaseui:firebase-ui-auth:6.2.1"
firebase_database = "com.google.firebase:firebase-firestore-ktx:21.5.0"
firebase_messaging = "com.google.firebase:firebase-messaging:20.2.3"
rx_java = "io.reactivex.rxjava2:rxjava:2.2.19"
rx_android = "io.reactivex.rxjava2:rxandroid:2.1.1"
rx_kotlin = "io.reactivex.rxjava2:rxkotlin:2.4.0"
rx_binding = "com.jakewharton.rxbinding2:rxbinding-kotlin:2.2.0"
mvrx = "com.airbnb.android:mvrx:1.2.1"
material = "com.google.android.material:material:1.0.0"
picasso = "com.squareup.picasso:picasso:2.71828"
timber = "com.jakewharton.timber:timber:4.7.1"
koin = "org.koin:koin-android:1.0.2"
koin_viewmodel = "org.koin:koin-android-viewmodel:1.0.2"
# Testing
junit = "junit:junit:4.13.2"
mockito_core = "org.mockito:mockito-core:5.5.0"
mockito_inline = "org.mockito:mockito-inline:5.2.0"
mockito_kotlin = "org.mockito.kotlin:mockito-kotlin:4.1.0"

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
android_library = { id = "com.android.library", version.ref = "agp" }
google_services = { id = "com.google.gms.google-services", version.ref = "google_services" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_android_extensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "kotlin" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.44.0" }
